using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Sound : MonoBehaviour
{
	public static Sound Instance {get; set;}
	public AudioSource music; 
	private void Awake()
	{
		if (Instance == null)
		{
			Instance = this;
			DontDestroyOnLoad(this);
	}
	else
	{
		Destroy(gameObject);
	 }
	}
	// Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

	public void MuteSound()
	{
		if(music.mute == false)
		{
			music.mute=true;
		}
		else
		{
			music.mute= false;
		}
	}
}
